version: '3'

services:
  mongodb:
    image: mongo:4.1.6
    ports:
      - "27017:27017"
    volumes:
      - ./server/database:/app/database
  node:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app